[package]
name = "rustsdlplayer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gstreamer = "0.19.5"
gstreamer-app = "0.19.2"
gstreamer-video = "0.19.5"
url = "2.3.1"
sdl2 = "0.35.2"
